### ISSUE TITLE
Build Project will not build the selected project

### ISSUE THREAD

**Issue by Domain** [buggins/dlangide#334] opened 2017-09-29 03:08 UTC
When I right click on a project and select Build Project, dlangide will not build the selected project, it just build main package.

**Comment by buggins** [comment] 2017-10-02 09:10
Works for me.
Scenario: 
* workspace with two projects, project1 and project2.
* project1 is set as default project.
* project1 is selected in workspace tree
* Right click on project2 in workspace tree, choose Build Project context menu item.
* DUB is invoked for project2.

Are you sure you are using recent version of dlangide?

**Comment by buggins** [comment] 2017-10-03 06:32
Closing as fixed in one of recent releases.
Please reopen if you still can reproduce it on latest build.

**Closed by buggins** 2017-10-03 06:32 UTC
Labels: bug

**Comment by Domain** [comment] 2017-10-09 03:54
@buggins Still there. This is my dub.json:
<pre>{
	"name": "zero",
	"authors": ["Domain"],
	"description": "A game framework",
	"copyright": "Copyright © 2017, Domain",
	"license": "proprietary",
	"targetType": "none",
	"dependencies": {
		"zero:zero": "*",
		"zero:bootstrap": "*",
		"zero:hosting": "*"
	},
	"subPackages": [
		{
			"name": "zero",
			"targetType": "library",
			"targetPath": "lib",
			"sourcePaths": [
				"src/zero" 
			],
			"dependencies": {
				"pegged": "~>0.4.2",
				"msgpack-d": "~>1.0.0-beta.6"
			}
		},
		{
			"name": "bootstrap",
			"targetType": "executable",
			"targetPath": "bin",
			"targetName": "launch",
			"sourcePaths": [
				"src/bootstrap" 
			],
			"dependencies": {
				"zero:zero": "*"
			}
		},
		{
			"name": "hosting",
			"targetType": "executable",
			"targetPath": "bin/0.0.1",
			"targetName": "zero",
			"sourcePaths": [
				"src/hosting" 
			],
			"dependencies": {
				"zero:zero": "*"
			}
		}
	]
}</pre>
I want to build bootstrap, and the compile log is:
`C:\D\dmd2\windows\bin\dub.exe build --build-mode=allAtOnce --build=debug`
I think it should be:
`C:\D\dmd2\windows\bin\dub.exe build zero:bootstrap --build-mode=allAtOnce --build=debug`

**Comment by Domain** [comment] 2017-10-10 02:25
@buggins I cannot reopen this issue since you closed it.
