### ISSUE TITLE
Segfault on opening project or workspace

### ISSUE THREAD

**Issue by russel** [buggins/dlangide#242] opened 2017-08-25 08:10 UTC
Brand new build of DlangIDE on Debian Sid. Built using:

    dub build --compiler ldc2 --build release

bin/dlangide copied to ~/Built/bin since that is my directory for personally built stuff. Start DlangIDE with:

    dlangide

the initial dialogue appears. Click on "Open project or workspace…" and a segfault results.
```
|> dlangide 
Segmentation fault
```

**Comment by buggins** [comment] 2017-08-25 09:22
Are you sure you are using recent dlangide and dlangui version?
There was similar issue, which is already fixed.

**Comment by russel** [comment] 2017-08-25 14:02
It still has a problem, but now there is a message having updated to 8fffaa9e0976dd4eea3c2d1f73342838cfe96c06
```
|> dlangide 
2017-08-25 15:01:26.260 E  Unknown style ID requested: TERMINAL
Segmentation fault
```

**Comment by buggins** [comment] 2017-08-25 14:10
Looks like duplicate of #229.
Is it under linux?

**Comment by buggins** [comment] 2017-08-25 14:15
Not reproducible under Windows - both Win32 api and SDL configurations.

**Comment by russel** [comment] 2017-08-25 14:37
Yes it is Linux, I am currently on Debian Sid.

**Comment by buggins** [comment] 2017-08-25 14:40
Tried on Ubuntu 4.2016 - not reproduced

**Comment by buggins** [comment] 2017-08-25 14:42
Doesn't debug built give more messages in log?
    dub run --build=debug

**Comment by buggins** [comment] 2017-08-25 15:01
Probably fixed in v0.7.51

**Comment by russel** [comment] 2017-08-25 15:14
```
|> dub upgrade
Upgrading project in /home/Checkouts/Git/DlangIDE
Root package dlangide reference dlangui 0.9.98 cannot be satisfied.
```

I guess I am being to quick to try things out. ;-)

**Comment by buggins** [comment] 2017-08-25 15:58
dub repository seems like being updated with delay
try again in one hour

**Comment by and3md** [comment] 2017-08-25 16:44
I reproduced this issue. To reproduce it change this paths to something not exists in `settings.json`:
>    "pathHistory": {
>        "FILE_OPEN_WORKSPACE_PATH": "path",
>       "FILE_OPEN_PATH": "/path"`
>    }

Your fix from 0.9.98 need small improve:

        if (!_path.exists || !_path.isDir) {
            _path = currentDir;
            if (!_path.exists || !_path.isDir)
                _path = homePath;
        }

**Comment by buggins** [comment] 2017-08-25 16:56
done

**Comment by and3md** [comment] 2017-08-25 17:05
I just changed my project dir and dlangide start crash. Found accidentally :)

**Comment by buggins** [comment] 2017-08-28 10:25
Should be fixed now.

**Closed by buggins** 2017-08-28 10:25 UTC
