### ISSUE TITLE
file/open causes crash

### ISSUE THREAD

**Issue by logicfish** [buggins/dlangide#229] opened 2017-08-05 23:56 UTC
nothing in dcd.log - just an empty file.

**Comment by buggins** [comment] 2017-08-09 06:38
Cannot reproduce.
What is file extension and content?
Does it crash on any file or only some particular file?

**Comment by logicfish** [comment] 2017-08-09 14:13
It crashes on button click or menu command before dialog appears. this is on windows10 and linux. this is from ~master.  how do I enable logging?

**Comment by buggins** [comment] 2017-08-10 07:35
Win7 / ~master - both File / Open file.. and ctrl+o working ok.
Are you sure dependencies (especially dlangui) are up to date?
What if you run it with `dub upgrade --force-remove && dub run`?

**Comment by logicfish** [comment] 2017-08-11 12:30
x86_64 win10 - crashes with no error.
x86 - see error below.
![untitled](https://user-images.githubusercontent.com/1307024/29212994-34c89a44-7e99-11e7-861e-692e12978e89.png)

**Comment by logicfish** [comment] 2017-08-11 12:41
linux-64
2017-08-11 12:39:39.102 D  FileDialog.openDirectory(/h.......)
Program exited with code -11

**Comment by buggins** [comment] 2017-08-11 13:37
Line 208
            _popup = _parentWindow.showPopup(_frame);

Looks like _parentWindow is null... No idea how it could happen.

**Comment by and3md** [comment] 2017-08-11 16:43
I think there are exception in `openDirectory()` called form `FileDialog.initialize()` then when try show message box  window is not created yet.

Try comment line 267 of `FileDialog.openDirectory()` (filedlg.d):

>            //import dlangui.dialogs.msgbox;
>            //auto msgBox = new MessageBox(UIString.fromId("MESSAGE_ERROR"c), UIString.fromRaw(e.msg.toUTF32), window());
>            //msgBox.show();

and add a simple log in this place:

`Log.d("Error is here ", e.msg);`

**Comment by buggins** [comment] 2017-08-25 15:01
Probably fixed in v0.7.51

**Closed** 2017-08-28 10:32 UTC
Labels: bug
