### ISSUE TITLE
E  Unknown style ID requested: TERMINAL

### ISSUE THREAD

**Issue by kunftep** [buggins/dlangide#330] opened 2017-09-26 17:45 UTC
i have a problem getting it to run:

	2017-09-26 19:22:45.396 E  Unknown style ID requested: TERMINAL
	Program exited with code -11

here is the full attempt:

	[mm]~/eclipseWorkspace>git clone --recursive https://github.com/buggins/dlangide.git
	...
	[mm]~/eclipseWorkspace>cd dlangide/
	[mm]~/eclipseWorkspace/dlangide>dub build --force
	Performing "debug" build using dmd for x86_64.
	emsi_containers 0.5.3: building configuration "library"...
	libdparse 0.7.1: building configuration "library"...
	dsymbol 0.2.9: building configuration "library"...
	msgpack-d 1.0.0-beta.6: building configuration "library"...
	dcd 0.9.1: building configuration "library"...
	derelict-util 2.0.6: building configuration "library"...
	derelict-ft 1.1.3: building configuration "library"...
	derelict-gl3 1.0.23: building configuration "library"...
	derelict-sdl2 2.0.2: building configuration "library"...
	dlangui 0.9.149: building configuration "default"...
	dlangide 0.8.0: building configuration "default"...
	Linking...

	[mm]~/eclipseWorkspace/dlangide>dub run
	Performing "debug" build using dmd for x86_64.
	emsi_containers 0.5.3: target for configuration "library" is up to date.
	libdparse 0.7.1: target for configuration "library" is up to date.
	dsymbol 0.2.9: target for configuration "library" is up to date.
	msgpack-d 1.0.0-beta.6: target for configuration "library" is up to date.
	dcd 0.9.1: target for configuration "library" is up to date.
	derelict-util 2.0.6: target for configuration "library" is up to date.
	derelict-ft 1.1.3: target for configuration "library" is up to date.
	derelict-gl3 1.0.23: target for configuration "library" is up to date.
	derelict-sdl2 2.0.2: target for configuration "library" is up to date.
	dlangui 0.9.149: target for configuration "default" is up to date.
	dlangide 0.8.0: target for configuration "default" is up to date.
	To force a rebuild of up-to-date targets, run again with --force.
	Running ./bin/dlangide 
	2017-09-26 19:22:44.704 I  Log level changed to Trace
	2017-09-26 19:22:44.704 I  Logger is initialized
	2017-09-26 19:22:44.704 V  DerelictFT: Loading FreeType library
	2017-09-26 19:22:44.705 V  DerelictFT: Missing symbols callback is registered
	2017-09-26 19:22:44.709 V  DerelictFT: Loaded
	2017-09-26 19:22:44.709 V  Initializing FreeType library
	2017-09-26 19:22:44.714 I  Getting list of fonts using FontConfig
	2017-09-26 19:22:45.002 I  FontConfig: 4228 font files registered in 288ms
	2017-09-26 19:22:45.002 D  initResourceManagers()
	2017-09-26 19:22:45.006 I  Creating ImageCache
	2017-09-26 19:22:45.006 I  Creating DrawableCache
	2017-09-26 19:22:45.006 D  Calling initSharedResourceManagers()
	2017-09-26 19:22:45.006 D  Calling initStandardEditorActions()
	2017-09-26 19:22:45.006 D  Calling registerStandardWidgets()
	2017-09-26 19:22:45.006 D  Registering standard widgets for DML
	2017-09-26 19:22:45.006 D  initResourceManagers() -- finished
	2017-09-26 19:22:45.168 D  Creating default theme
	2017-09-26 19:22:45.168 I  sdlUpdateScreenDpi: SCREEN_DPI=120
	2017-09-26 19:22:45.168 I  sdlUpdateScreenDpi: SCREEN_DPI is changed from 96 to 120
	2017-09-26 19:22:45.168 V  uiTheme setting new theme theme_default
	2017-09-26 19:22:45.174 I  Applying loaded theme theme_default
	2017-09-26 19:22:45.174 V  uiTheme setting new theme ide_theme_default
	2017-09-26 19:22:45.179 I  Applying loaded theme ide_theme_default
	2017-09-26 19:22:45.180 V  setDefaultLanguageAndThemeIfNecessary : setting UI language
	2017-09-26 19:22:45.180 V  Loading language file
	2017-09-26 19:22:45.180 D  Loading string resources from file @embedded@/std_en.ini
	2017-09-26 19:22:45.180 D  Loading string resources from file @embedded@/en.ini
	2017-09-26 19:22:45.181 V  Calling onThemeChanged
	2017-09-26 19:22:45.182 D  Creating SDL window
	2017-09-26 19:22:45.183 I  Trying to create OpenGL 3.2 context
	2017-09-26 19:22:45.184 E  SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig
	2017-09-26 19:22:45.185 W  trying other versions of OpenGL
	2017-09-26 19:22:45.185 I  Trying to create OpenGL 3.3 context
	2017-09-26 19:22:45.185 E  SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig
	2017-09-26 19:22:45.185 I  Trying to create OpenGL 3.2 context
	2017-09-26 19:22:45.185 E  SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig
	2017-09-26 19:22:45.185 I  Trying to create OpenGL 3.1 context
	2017-09-26 19:22:45.185 E  SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig
	2017-09-26 19:22:45.185 I  Trying to create OpenGL 2.1 context
	2017-09-26 19:22:45.188 I  Created successfully
	2017-09-26 19:22:45.188 V  Reloading DerelictGL3
	2017-09-26 19:22:45.189 V  Reloading DerelictGL
	2017-09-26 19:22:45.190 D  glSupport not initialized: trying to create
	2017-09-26 19:22:45.190 V  OpenGL is initialized ok
	2017-09-26 19:22:45.190 I  OpenGL is enabled
	2017-09-26 19:22:45.190 D  Loading image from file @embedded@/dlangui-logo1.png
	2017-09-26 19:22:45.191 I  sdlUpdateScreenDpi: SCREEN_DPI=120
	2017-09-26 19:22:45.207 D  Loading image from file @embedded@/list_item_selected.9.png
	2017-09-26 19:22:45.207 D  Loading image from file @embedded@/list_item_focused.9.png
	2017-09-26 19:22:45.207 D  Loading image from file @embedded@/list_item_hovered.9.png
	2017-09-26 19:22:45.233 I  ptty device created: /dev/pts/1
	2017-09-26 19:22:45.234 D  TerminalDevice threadProc() enter
	2017-09-26 19:22:45.253 D  Searching for compiler path: dmd
	2017-09-26 19:22:45.267 D  compiler output:
	/home/mm/.dlangide/tmp_dummy_file_to_get_import_paths.d(1): Error: module module_that_does_not_exist is in file 'module_that_does_not_exist.d' which cannot be read
	import path[0] = /usr/include/dmd/phobos
	import path[1] = /usr/include/dmd/druntime/import

	2017-09-26 19:22:45.267 D  import path found: `/usr/include/dmd/phobos`
	2017-09-26 19:22:45.267 D  import path found: `/usr/include/dmd/druntime/import`
	2017-09-26 19:22:45.267 D  dmd imports:["/usr/include/dmd/phobos", "/usr/include/dmd/druntime/import"]
	2017-09-26 19:22:45.268 D  Searching for compiler path: gdc
	2017-09-26 19:22:45.383 D  compiler output:
	/home/mm/.dlangide/tmp_dummy_file_to_get_import_paths.d:1:8: error: module module_that_does_not_exist is in file 'module_that_does_not_exist.d' which cannot be read
	 import module_that_does_not_exist;
			^
	import path[0] = /usr/lib/gcc/x86_64-linux-gnu/5/include/d

	2017-09-26 19:22:45.383 D  import path found: `/usr/lib/gcc/x86_64-linux-gnu/5/include/d`
	2017-09-26 19:22:45.383 D  gdc imports:["/usr/lib/gcc/x86_64-linux-gnu/5/include/d"]
	2017-09-26 19:22:45.385 D  Shortcut actions loaded
	2017-09-26 19:22:45.385 V  uiTheme setting new theme ide_theme_dark
	2017-09-26 19:22:45.395 I  Applying loaded theme ide_theme_dark
	2017-09-26 19:22:45.396 E  Unknown style ID requested: TERMINAL
	Program exited with code -11
	[mm]~/eclipseWorkspace/dlangide>

**Comment by buggins** [comment] 2017-09-27 05:03
missing style should not be a problem.
There is some another root cause of crash.

**Comment by buggins** [comment] 2017-09-27 06:44
Looks like crash occurs if dark theme is selected.
Does it fix crash if you edit file ~/.dlangide/settings.json
Change theme to

        "theme": "ide_theme_default",

**Comment by kunftep** [comment] 2017-09-27 07:04
there is no file 'settings.json'

	[mm]~/eclipseWorkspace/dlangide>find | grep -i setting
	./src/dlangide/ui/settings.d
	./src/dlangide/workspace/idesettings.d
	./src/dlangide/workspace/projectsettings.d
	./src/dlangide/workspace/workspacesettings.d
	./workspaces/sample1/sampleproject1/sampleproject1.settings
	./workspaces/sample1/sample1.dlangidews.settings
	./workspaces/sample1/sampleproject2/sampleproject2.settings
	[mm]~/eclipseWorkspace/dlangide>

**Comment by buggins** [comment] 2017-09-27 07:08
Should be fixed in v0.8.1

settings json is located in home directory, .dlangide subdir

**Comment by kunftep** [comment] 2017-09-27 07:11
yes, sorry. it works and starts fine. changing to dark theme in preferences causes crash as you already know.
thank you!

**Comment by kunftep** [comment] 2017-09-27 07:16
well, it does not exactly crash here. exits with -11.

**Comment by buggins** [comment] 2017-09-27 07:28
It's actually crash.
I've fixed it - in dlangui v0.9.150 but it's not yet indexed by DUB registry.
Once it's ready, you can to rebuild dlangide with dlangui v0.9.150 (after dub upgrade).

**Comment by kunftep** [comment] 2017-09-27 07:39
yes, i got

	Root package dlangide reference dlangui ~>0.9.150 cannot be satisfied

i will try later.

**Closed** 2017-09-27 07:49 UTC
Labels: bug

**Comment by buggins** [comment] 2017-09-27 07:51
DUB registry catched up v0.9.150

**Comment by kunftep** [comment] 2017-09-27 07:58
starts up fine and i can also change to dark theme. thanks again!

**Comment by buggins** [comment] 2017-09-27 08:05
Thank you!
