### ISSUE TITLE
file explorer should show all files

### ISSUE THREAD

**Issue by keywan-ghadami** [buggins/dlangide#110] opened 2016-01-24 09:30 UTC
File explorer show only d files and folders
But it should also show other files .

use case for me is editing the dub files or theme xml files. Maybe it should be configureable by filetype if a file should openend in a special external editor.

**Comment by buggins** [comment] 2016-01-25 13:39
In FileDialog, there is file type combo box in right bottom corner.
Switch it to "All Files" to see all files.

**Comment by buggins** [comment] 2016-01-25 13:41
Moreover, XML and JSON files are treated as Source files and visible by default.
Open some project, then use "Open File" - you should see xmls and jsons even w/o changing of file type filter.

**Comment by buggins** [comment] 2016-01-27 06:05
Closing as not a bug

**Closed by buggins** 2016-01-27 06:05 UTC
