### ISSUE TITLE
dub build hangs

### ISSUE THREAD

**Issue by Valera** [buggins/dlangide#140] opened 2016-02-25 12:41 UTC
When I try to do "dub build" in dlangide directory, it hangs. I tried to build dlangui in separate directory and do "dub add-path pathToDlangUI" but the problem remains.

"dub --vvervose build" shows tons of this output:

Dependency derelict-gl3 -> derelict-util >=1.0.3 mismatches with selected version invalid (ci=12)
Interation (ci=12) dcd 0.7.5, libdparse invalid, experimental_allocator invalid, dsymbol invalid, emsi_containers invalid, msgpack-d invalid, dlangui 0.7.72, x11 1.0.13, derelict-ft 1.1.0, derelict-util invalid, derelict-sdl2 1.2.8, dsfml ~2.0, derelict-gl3 1.0.7 (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Dependency dlangui -> derelict-ft >=1.0.2 <1.1.0 mismatches with selected version 1.1.0 (ci=8)
Dependency derelict-ft -> derelict-util >=1.0.3 mismatches with selected version invalid (ci=9)
Dependency dlangui -> derelict-sdl2 >=1.9.7 <1.10.0 mismatches with selected version 1.2.8 (ci=10)
Dependency derelict-sdl2 -> derelict-util >=1.0.2 mismatches with selected version invalid (ci=10)
Dependency dlangui -> dsfml >=2.1.0 <2.2.0 mismatches with selected version ~2.0 (ci=11)
Dependency dlangui -> derelict-gl3 >=1.0.16 <1.1.0 mismatches with selected version 1.0.6 (ci=12)
Dependency derelict-gl3 -> derelict-util >=1.0.2 mismatches with selected version invalid (ci=12)

**Comment by buggins** [comment] 2016-02-26 10:18
Try `dub upgrade --force-remove`

**Comment by Valera** [comment] 2016-02-26 18:50
No, it doesn't help. Even if I delete ~/.dub it still hangs. When I pass --verbose it is clearly visible that dub loops over different combinations of package versions and no combinations is valid.

dub --vverbose upgrade --force-remove 2>&1 | head -n 120

Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/vfedotov/.dub/packages/local-packages.json
Determined package version using GIT: dlangide 0.5.66+commit.2.ga777f08
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/vfedotov/.dub/packages/local-packages.json
Collecting dependencies for dlangide
Version selection for dependency dcd (dcd) of dlangide is missing.
Version selection for dependency dlangui (dlangui) of dlangide is missing.
Upgrading project in /home/vfedotov/projects/dlangide
Search for versions of dcd (1 package suppliers)
Downloading metadata for dcd
Getting from http://code.dlang.org/packages/dcd.json
Getting http://code.dlang.org/packages/dcd.json...
Search for versions of libdparse (1 package suppliers)
Downloading metadata for libdparse
Getting from http://code.dlang.org/packages/libdparse.json
Getting http://code.dlang.org/packages/libdparse.json...
Search for versions of experimental_allocator (1 package suppliers)
Downloading metadata for experimental_allocator
Getting from http://code.dlang.org/packages/experimental_allocator.json
Getting http://code.dlang.org/packages/experimental_allocator.json...
Search for versions of dsymbol (1 package suppliers)
Downloading metadata for dsymbol
Getting from http://code.dlang.org/packages/dsymbol.json
Getting http://code.dlang.org/packages/dsymbol.json...
Search for versions of emsi_containers (1 package suppliers)
Downloading metadata for emsi_containers
Getting from http://code.dlang.org/packages/emsi_containers.json
Getting http://code.dlang.org/packages/emsi_containers.json...
Search for versions of msgpack-d (1 package suppliers)
Downloading metadata for msgpack-d
Getting from http://code.dlang.org/packages/msgpack-d.json
Getting http://code.dlang.org/packages/msgpack-d.json...
Search for versions of dlangui (1 package suppliers)
Downloading metadata for dlangui
Getting from http://code.dlang.org/packages/dlangui.json
Getting http://code.dlang.org/packages/dlangui.json...
Search for versions of x11 (1 package suppliers)
Downloading metadata for x11
Getting from http://code.dlang.org/packages/x11.json
Getting http://code.dlang.org/packages/x11.json...
Search for versions of derelict-ft (1 package suppliers)
Downloading metadata for derelict-ft
Getting from http://code.dlang.org/packages/derelict-ft.json
Getting http://code.dlang.org/packages/derelict-ft.json...
Search for versions of derelict-util (1 package suppliers)
Downloading metadata for derelict-util
Getting from http://code.dlang.org/packages/derelict-util.json
Getting http://code.dlang.org/packages/derelict-util.json...
Search for versions of derelict-sdl2 (1 package suppliers)
Downloading metadata for derelict-sdl2
Getting from http://code.dlang.org/packages/derelict-sdl2.json
Getting http://code.dlang.org/packages/derelict-sdl2.json...
Search for versions of dsfml (1 package suppliers)
Downloading metadata for dsfml
Getting from http://code.dlang.org/packages/dsfml.json
Getting http://code.dlang.org/packages/dsfml.json...
Search for versions of derelict-gl3 (1 package suppliers)
Downloading metadata for derelict-gl3
Getting from http://code.dlang.org/packages/derelict-gl3.json
Getting http://code.dlang.org/packages/derelict-gl3.json...
Configurations used for dependency resolution:
  libdparse (1): [invalid, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.1, 0.1.0, ~master]
  experimental_allocator (2): [invalid, 2.70.0-b1, ~master]
  dsymbol (3): [invalid, 0.1.1, 0.1.0, ~master]
  x11 (7): [invalid, 1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, ~master]
  dcd (0): [invalid, 0.7.5, 0.8.0-beta2, 0.8.0-beta1]
  msgpack-d (5): [invalid, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 1.0.0-beta.2, 1.0.0-beta.1, ~master, ~support-unpack-struct-withFieldName, ~fix-enum-conflict]
  derelict-ft (8): [invalid, 1.1.0, 1.0.2, 1.0.1, 1.0.0, ~master, ~2.6, ~2.5]
  derelict-util (9): [invalid, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.9.1, 1.9.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0, ~master, ~2.0]
  dlangui (6): [invalid, 0.7.72, 0.7.71, 0.7.70]
  derelict-sdl2 (10): [invalid, 2.0.0, 1.9.7, 1.9.6, 1.9.5, 1.9.4, 1.9.3, 1.9.2, 1.9.1, 1.9.0, 1.2.16, 1.2.15, 1.2.14, 1.2.13, 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.17, 1.1.16, 1.1.15, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.19, 1.0.18, 1.0.17, 1.0.16, 1.0.15, 1.0.14, 1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, ~master, ~2.0.4, ~2.0.2, ~2.0.1, ~2.0.0]
  dsfml (11): [invalid, 2.1.0, ~master, ~2.0]
  emsi_containers (4): [invalid, 0.3.0, ~master]
  derelict-gl3 (12): [invalid, 1.0.18, 1.0.17, 1.0.16, 1.0.15, 1.0.14, 1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, ~master, ~contexts]
Interation (ci=0) dcd invalid (C), libdparse invalid (C), experimental_allocator invalid (C), dsymbol invalid (C), emsi_containers invalid (C), msgpack-d invalid (C), dlangui invalid (C), x11 invalid (C), derelict-ft invalid (C), derelict-util invalid (C), derelict-sdl2 invalid (C), dsfml invalid (C), derelict-gl3 invalid (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Interation (ci=6) dcd 0.7.5, libdparse invalid, experimental_allocator invalid, dsymbol invalid, emsi_containers invalid, msgpack-d invalid, dlangui invalid (C), x11 invalid (C), derelict-ft invalid (C), derelict-util invalid (C), derelict-sdl2 invalid (C), dsfml invalid (C), derelict-gl3 invalid (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Dependency dlangui -> x11 >=1.0.9 <1.1.0 mismatches with selected version invalid (ci=7)
Interation (ci=7) dcd 0.7.5, libdparse invalid, experimental_allocator invalid, dsymbol invalid, emsi_containers invalid, msgpack-d invalid, dlangui 0.7.72, x11 invalid (C), derelict-ft invalid (C), derelict-util invalid (C), derelict-sdl2 invalid (C), dsfml invalid (C), derelict-gl3 invalid (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Dependency dlangui -> derelict-ft >=1.0.2 <1.1.0 mismatches with selected version invalid (ci=8)
Interation (ci=8) dcd 0.7.5, libdparse invalid, experimental_allocator invalid, dsymbol invalid, emsi_containers invalid, msgpack-d invalid, dlangui 0.7.72, x11 1.0.13, derelict-ft invalid (C), derelict-util invalid (C), derelict-sdl2 invalid (C), dsfml invalid (C), derelict-gl3 invalid (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Dependency dlangui -> derelict-ft >=1.0.2 <1.1.0 mismatches with selected version 1.1.0 (ci=8)
Dependency derelict-ft -> derelict-util >=1.0.3 mismatches with selected version invalid (ci=9)
Dependency dlangui -> derelict-sdl2 >=1.9.7 <1.10.0 mismatches with selected version invalid (ci=10)
Interation (ci=10) dcd 0.7.5, libdparse invalid, experimental_allocator invalid, dsymbol invalid, emsi_containers invalid, msgpack-d invalid, dlangui 0.7.72, x11 1.0.13, derelict-ft 1.1.0, derelict-util invalid, derelict-sdl2 invalid (C), dsfml invalid (C), derelict-gl3 invalid (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Dependency dlangui -> derelict-ft >=1.0.2 <1.1.0 mismatches with selected version 1.1.0 (ci=8)
Dependency derelict-ft -> derelict-util >=1.0.3 mismatches with selected version invalid (ci=9)
Dependency dlangui -> derelict-sdl2 >=1.9.7 <1.10.0 mismatches with selected version 2.0.0 (ci=10)
Dependency derelict-sdl2 -> derelict-util >=2.0.4 <2.1.0 mismatches with selected version invalid (ci=10)
Dependency dlangui -> dsfml >=2.1.0 <2.2.0 mismatches with selected version invalid (ci=11)
Interation (ci=11) dcd 0.7.5, libdparse invalid, experimental_allocator invalid, dsymbol invalid, emsi_containers invalid, msgpack-d invalid, dlangui 0.7.72, x11 1.0.13, derelict-ft 1.1.0, derelict-util invalid, derelict-sdl2 2.0.0, dsfml invalid (C), derelict-gl3 invalid (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Dependency dlangui -> derelict-ft >=1.0.2 <1.1.0 mismatches with selected version 1.1.0 (ci=8)
Dependency derelict-ft -> derelict-util >=1.0.3 mismatches with selected version invalid (ci=9)
Dependency dlangui -> derelict-sdl2 >=1.9.7 <1.10.0 mismatches with selected version 2.0.0 (ci=10)
Dependency derelict-sdl2 -> derelict-util >=2.0.4 <2.1.0 mismatches with selected version invalid (ci=10)
Dependency dlangui -> derelict-gl3 >=1.0.16 <1.1.0 mismatches with selected version invalid (ci=12)
Interation (ci=12) dcd 0.7.5, libdparse invalid, experimental_allocator invalid, dsymbol invalid, emsi_containers invalid, msgpack-d invalid, dlangui 0.7.72, x11 1.0.13, derelict-ft 1.1.0, derelict-util invalid, derelict-sdl2 2.0.0, dsfml 2.1.0, derelict-gl3 invalid (C)
Dependency dcd -> libdparse >=0.3.0 <0.4.0 mismatches with selected version invalid (ci=1)
Dependency dlangui -> derelict-ft >=1.0.2 <1.1.0 mismatches with selected version 1.1.0 (ci=8)
Dependency derelict-ft -> derelict-util >=1.0.3 mismatches with selected version invalid (ci=9)
Dependency dlangui -> derelict-sdl2 >=1.9.7 <1.10.0 mismatches with selected version 2.0.0 (ci=10)
Dependency derelict-sdl2 -> derelict-util >=2.0.4 <2.1.0 mismatches with selected version invalid (ci=10)
Dependency derelict-gl3 -> derelict-util >=1.0.3 mismatches with selected version invalid (ci=12)

**Comment by buggins** [comment] 2016-02-27 19:16
did you try to remove dub selections.json?

**Comment by Valera** [comment] 2016-02-27 20:04
No, it doesn't help. I get the same behaviour after creating a new user and executing

git clone https://github.com/buggins/dlangide.git
cd dlangide/
dub --vverbose build

**Comment by buggins** [comment] 2016-02-29 06:58
Works for me on Linux + DUB 0.9.24, win32 - DUB ~master built in Jan 2016

What is your dub version?

**Comment by Valera** [comment] 2016-02-29 18:56
0.9.24 for x86-64 Linux.
Ubuntu 15.10

In fact, I get the same error on two computers even after creating a fresh new user and trying to build dlangide. I can repeat this with

wget http://code.dlang.org/files/dub-0.9.24-linux-x86_64.tar.gz
tar xfvz dub-0.9.24-linux-x86_64.tar.gz
git clone https://github.com/buggins/dlangide.git
../dub --vverbose build

**Comment by rjframe** [comment] 2016-03-01 03:33
I had the same problem with Debian 8 64-bit, though it looks like this might be [Dub's issue 652](https://github.com/D-Programming-Language/dub/issues/652). Changing the dependency version for dlangui to "==0.7.68" built much faster. Alternatively, maybe letting it run all night will work?

**Comment by Valera** [comment] 2016-03-01 19:25
Thanks, "==0.7.68" helps.

**Comment by Masclaux** [comment] 2016-03-05 13:59
Hi . same on windows  7 build hand on dereclit dependencie and after waiting a "few" hours installation continue and finish.

**Comment by keywan-ghadami** [comment] 2016-03-06 09:22
i had same issue, thanks to the other comments i found two solutions working for me
'==' instead of '~>' in dub.json
 "dependencies": {
        "dlangui": "==0.7.74",
        "dcd": "==0.7.5"
    },
or using dub build from the current master branch
(git clone + build.sh worked good)

**Comment by buggins** [comment] 2016-03-09 06:19
Updated DCD to 8.0 and dlangui to 0.7.75
Is issues still reproducible?

**Comment by Masclaux** [comment] 2016-03-09 08:16
Hi 

For me is ok.

**Comment by buggins** [comment] 2016-03-10 08:57
If no complains, I'll close this issue in a few days

**Comment by aravol** [comment] 2016-03-12 13:48
Gettting this problem now on Windows

**Comment by keywan-ghadami** [comment] 2016-03-12 22:37
Maybe i found an other time consuming dependencie in dub.json in dlangui there is sometimes derelict-ft": "~>1.0.2" and once derelict-ft": "~>1.1.0", i think it should be everywhere derelict-ft": "~>1.1.0".

**Comment by buggins** [comment] 2016-03-16 13:55
Probably fixed in v0.5.70 - dlangui dependency version is changed to == from ~>

**Comment by wyrex** [comment] 2016-03-16 14:17
Seems to work fine with that change.

**Comment by buggins** [comment] 2016-03-17 05:00
Ok. Will keep == in dlangui dependency unless DUB is fixed.

**Closed by buggins** 2016-03-17 05:00 UTC
