### ISSUE TITLE
code completion using DCD

### ISSUE THREAD

**Issue by Extrawurst** [buggins/dlangide#20] opened 2015-02-10 21:31 UTC
somewhat related to issue #5...

see forum for reference: http://forum.dlang.org/post/wzsoaeqdnftlwwspdazm@forum.dlang.org

maybe coedit's way of using DCD for code completion is an inspiration:
https://github.com/BBasile/Coedit/blob/master/src/ce_dcd.pas#L215

important to note is, that since DCD parses the code itself one needs to save unsaved changes in the file in a tmpfile to have DCD parse it, which should not be a problem and be significantly easier and safer than integrating libdparse yourself. SOA for the win ;)

**Comment by Hackerpilot** [comment] 2015-02-10 22:22
> important to note is, that since DCD parses the code itself one needs to save unsaved changes in the file in a tmpfile to have DCD parse it, which should not be a problem and be significantly easier and safer than integrating libdparse yourself. SOA for the win ;)

dcd-client accepts input from a file or stdin. Saving to a temporary file is not necessary.

**Comment by Extrawurst** [comment] 2015-02-11 06:45
Even better!!

**Comment by buggins** [comment] 2015-02-11 18:02
it could be easy solution just to integrade dcd into app - run it in separate thread and pass parameters and get result directly in D code.
DCD might be modified to be able building as library with communication and interface related stuff stripped out.
But there is a big problem: it's licensed under GPL3 - and incompatible with Boost license IMHO.

**Comment by Extrawurst** [comment] 2015-02-11 18:45
So back to running it as a seperated process

**Comment by Freakazo** [comment] 2015-02-11 19:13
How would I display the suggestions?

**Comment by Extrawurst** [comment] 2015-02-11 21:01
maybe a popup menu ?
see example of dlangui for that: https://github.com/buggins/dlangui/blob/master/examples/example1/src/example1.d#L287

but maybe another dedicated window for this would be more appropriate

**Comment by buggins** [comment] 2015-02-12 05:45
while icon + text is enough, we can use popup menu

**Comment by buggins** [comment] 2015-02-12 05:47
are you planning to run dcd-client executable to invoke dcd?
I think we can just use sockets to connect to dcd directly.

**Comment by Freakazo** [comment] 2015-02-13 21:15
Yup, as it currently stands I'm using dcd-client to communicate with dcd-server. Having a look at dcd-client source code it shouldn't be hard to replicate its behaviour.

At the moment I'm just finishing up the basic auto completion part and then I'll send a pull request so that the code can be reviewed.

**Comment by buggins** [comment] 2015-02-17 13:11
Merged pull request and as well did some refactoring and improvements.

**Comment by Revito** [comment] 2015-02-17 15:32
You forgot to upload _dcd-client.exe_.

**Comment by buggins** [comment] 2015-02-17 19:19
Yes, thanks. Will submit it tomorrow. So far you can build it yourself.

**Comment by buggins** [comment] 2015-02-19 08:43
Experimenting with direct using of libdparse

**Comment by Freakazo** [comment] 2015-02-20 01:29
Ah, that would definitely work much better than using it indirectly through dcd.

**Comment by buggins** [comment] 2015-02-20 08:16
So far, I'm trying to implement GoToDefinition feature with libdparse.

**Comment by keywan-ghadami** [comment] 2016-01-01 01:44
I am going to improve dub support of that libparse and related packages. I have registered dub packages for libparsed, dsymbol and dcd. I guess that will it make it easer to integrate them.

**Comment by buggins** [comment] 2016-01-02 16:34
Let's use your DCD integration implementation so far.

**Comment by buggins** [comment] 2016-01-11 07:47
Fixed VisualD and Mono-D projects for new DCD integration.
README is updated with dependency cloning instructions

**Comment by buggins** [comment] 2016-01-11 07:48
BTW, code completion and finding references doesn't work for me

**Comment by keywan-ghadami** [comment] 2016-01-12 07:16
It stopped working for me too (linux) , i have some ideas what it could be (working path, modulecache, dependencies...). I checked the code from dcd server.d which is NOT used by dlangide and the only difference i found was that it sets a loglevel and changes the working directory - (and it does not set a logger). Maybe we need to set the working directory to something specific before calling DCD (seems it makes differece if it runs in linux or windows). Sorry for all the trouble...

**Comment by buggins** [comment] 2016-01-12 07:40
Fixed problem with new DUB version today.
It looks like new DUB fetches dependencies into subdirectories.
As a result, dlangide did not find dependency projects.

**Comment by buggins** [comment] 2016-01-12 07:51
Reproduced non-working GoToDefinition in single file project.
In some cases position is determined wrongly.

Source lines:
    auto foo = new Foo();
    writeln("Hello World!");

DlangIDE log:
2016-01-12 10:43:10.425 D  DCD Context: oo = new F|oo();
2016-01-12 10:43:10.426 D  DCD fileName:

DCD log:

2016-01-12T10:41:14.039:..\DCD\src\server\autocomplete.d:getSymbolsByTokenChain:743 Could not find declaration of "Hello World!" from position 240
2016-01-12T10:41:14.039:..\DCD\src\server\autocomplete.d:findDeclaration:135 Could not find symbol declaration

DCD looks up symbol one line lower than expected by DlangIDE

**Comment by Hackerpilot** [comment] 2016-01-12 23:10
I'm pretty sure that this isn't a DCD bug because all the other editor plugins work.

**Comment by buggins** [comment] 2016-01-13 06:03
Unfortunately I cannot reproduce it anymore since I modified source and did not save original.
Now it's working ok.

**Comment by buggins** [comment] 2016-01-15 07:11
Closing this issue since DCD integration seems done

**Closed by buggins** 2016-01-15 07:11 UTC
Labels: enhancement
